parameters:
  BuildPlatform: ''
  MSBuildPlatform: ''

steps:
- bash: |
    set -ex
    curl -L https://github.com/openblack/compile-farm/releases/download/windows-deps/windows-dependencies-${{ parameters.BuildPlatform }}.7z > windows-dependencies.7z
    7z x windows-dependencies.7z
    rm -f windows-dependencies.7z
    mv windows-dependencies/installed /c/vcpkg/
    rm -rf windows-dependencies
  displayName: 'Install vcpkg dependencies'
  workingDirectory: $(Build.ArtifactStagingDirectory)
- script: c:\vcpkg\vcpkg.exe integrate install
  displayName: 'Integrate vcpkg'
- bash: |
    set -ex
    curl -L https://github.com/openblack/bgfx.cmake/releases/download/latest/bgfx-windows-${{ parameters.MSBuildPlatform }}.7z > bgfx-windows.7z
    7z x bgfx-windows.7z -oc:/bgfx
    rm -f bgfx-windows.7z
  displayName: 'Download precompiled bgfx'
  workingDirectory: $(Build.ArtifactStagingDirectory)